server:
  port: 3004

spring:
  application:
    name: "Student-data"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default:zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost