server:
  port: 3002

spring:
  application:
    name: "Exam-Details"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka.healthcheck.enabled: true;
    service-url:
      default:zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost